#!/usr/bin/env ruby
require 'bundler/setup'

require 'barge'
require 'yaml'
require 'dotenv'
require "highline/import"
Dotenv.load unless ENV['DIGITALOCEAN_TOKEN']

unless ENV['DIGITALOCEAN_TOKEN']
  puts "Please set the DIGITALOCEAN_TOKEN environment variable"
  exit
end

barge = Barge::Client.new do |config|
    config.access_token = ENV['DIGITALOCEAN_TOKEN']
end

droplet_id=ARGV[0]
if droplet_id.nil?
  puts "Usage: destroy-droplet <droplet-id>"
  exit(1)
end

drop=barge.droplet.show(droplet_id)

input = ask "Destroy droplet #{drop.droplet.name} [#{droplet_id}] (WARNING: This is not reversible!) [y/N]: "

case input
when 'y','Y'
    puts "you got it"
else

    puts "no way"
end

d = barge.droplet.destroy(droplet_id)

if d.success?
  puts "Destroyed droplet #{d.droplet.name} with id #{d.droplet.id}"
else
  puts "It seems we failed to destroy the droplet: #{d.message}"
end
