#!/usr/bin/env ruby
require 'barge'
require 'dotenv'
Dotenv.load

unless ENV['DIGITALOCEAN_TOKEN']
  puts "Please set the DIGITALOCEAN_TOKEN environment variable"
  exit
end

barge = Barge::Client.new do |config|
    config.access_token = ENV['DIGITALOCEAN_TOKEN']
end

keys = barge.key.all[:ssh_keys].collect do |k|
  "#{k.name} -- id: #{k.id}"
end.sort

puts keys.join("\n")
