#!/usr/bin/env ruby
require 'bundler/setup'

require 'barge'
require 'dotenv'
Dotenv.load

unless ENV['DIGITALOCEAN_TOKEN']
  puts "Please set the DIGITALOCEAN_TOKEN environment variable"
  exit
end

barge = Barge::Client.new do |config|
    config.access_token = ENV['DIGITALOCEAN_TOKEN']
end

droplets = barge.droplet.all.droplets

droplets.each do |droplet|
  if droplet.networks.v4.nil?
    ip_address = "ip unknown"
  else
    ip_address = droplet.networks.v4[0].ip_address
  end
  puts "#{droplet.name} [#{droplet.status}] (id: #{droplet.id}) -- #{ip_address}"
end
