#!/usr/bin/env ruby
require 'bundler/setup'

require 'barge'
require 'dotenv'

Dotenv.load unless ENV['DIGITALOCEAN_TOKEN']

unless ENV['DIGITALOCEAN_TOKEN']
  puts "Please set the DIGITALOCEAN_TOKEN environment variable"
  exit
end

barge = Barge::Client.new do |config|
    config.access_token = ENV['DIGITALOCEAN_TOKEN']
end

images = barge.image.all.first[1]

if ['-a','--all'].find{ |a| ARGV.include? a }
  all = true
else
  all = false
end

myimages = images.collect {|i| i if all or i.public == false }.compact.collect do |x|
  "#{x.name} (id: #{x.id}) -- created at #{x.created_at}"
end.sort

puts myimages.join("\n")
