#!/usr/bin/env ruby

require 'barge'

barge = Barge::Client.new do |config|
    config.access_token = ENV['DIGITALOCEAN_TOKEN']
end

droplets = barge.droplet.all.droplets

droplets.each do |droplet|
    puts "#{droplet.name} [#{droplet.status}] (id: #{droplet.id}) -- #{droplet.networks.v4[0].ip_address}"
end
