#!/usr/bin/env ruby
require 'bundler/setup'

require 'barge'
require 'dotenv'
Dotenv.load unless ENV['DIGITALOCEAN_TOKEN']

unless ENV['DIGITALOCEAN_TOKEN']
  puts "Please set the DIGITALOCEAN_TOKEN environment variable"
  exit
end

barge = Barge::Client.new do |config|
    config.access_token = ENV['DIGITALOCEAN_TOKEN']
end

droplets = barge.droplet.all.droplets

droplets.each do |droplet|
  if droplet.networks.v4.nil?
    ip_address = "ip unknown"
  else
    pubnet = droplet.networks.v4.find { |n| n.type == 'public'}
    pub_ip = pubnet ? pubnet.ip_address : nil
    privnet = droplet.networks.v4.find { |n| n.type == 'private'}
    priv_ip = privnet ? privnet.ip_address : nil
  end
  puts "#{droplet.name} [#{droplet.status}] (id: #{droplet.id}) -- #{priv_ip} : #{pub_ip}"
end
